spring:

  # db 설정
  datasource:
    username: user_liquibase
    password: 1234
    url: jdbc:mysql://localhost:3306/db_liquibase?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

# 로그 설정
logging:
  level:
    root: info
